#!/bin/bash

function jenkins-dind-init() {

  if [ ! -z "$BAIDS_DEBUG" ]
  then
    set -x
  else
    set +x
  fi

  export ENVIRONMENT="$1"

  export PROJECT_NAME="jenkins-dind"
#  export ENV_VHOST="${ENVIRONMENT}-${PROJECT_NAME}.emergyalabs.com"
#  export VIRTUAL_HOSTS="$ENV_VHOST ${ENVIRONMENT}-backend-${PROJECT_NAME}.emergyalabs.com"
#

  export PROJECT_DIR="$( dirname $(readlink -f $(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ) )"
  export PROJECT_SOURCES_DIR="$PROJECT_DIR/src"
  export OVERLAYFS_WORKDIR="/tmp/jenkins-dind-overlayfs-workdir"
  export MERGED_BUILD_CONTEXT_DIR="/tmp/jenkins-dind-merged-build-context"
  export DATA_DIR="$PROJECT_DIR/data"

  export SSH_CREDENTIALS_DIR="$HOME/.ssh"

  export DOCKER_REGISTRY_URI="docker-registry.emergya.com:443"
  export DOCKER_IMAGE="emergya/${PROJECT_NAME}:latest"
  export DOCKER_COMPOSE_FILE="$PROJECT_DIR/${ENVIRONMENT}-compose.yml"

  export DOCKER_CONTAINER_NAME="$(echo $ENV_VHOST | sed -e 's|\.||g' -e 's|-||g')_${ENV_VHOST}_1"

  export DEVELOPER_USER="$(basename $HOME)"

  export HOST_UID=$(id -u)
  export HOST_GID=$(id -g)

}

